Description: Pattern with packages for h4213 configurations
Name: jolla-configuration-h4213
Requires:
- pattern:jolla-hw-adaptation-discovery

- droid-config-h4213-sailfish
- droid-config-h4213-pulseaudio-settings
- droid-config-h4213-policy-settings
- droid-config-h4213-preinit-plugin
- droid-config-h4213-flashing
- droid-config-h4213-bluez5
- droid-hal-version-h4213

- patterns-sailfish-applications
- patterns-sailfish-ui
- patterns-sailfish-cellular-apps

- sailfish-content-graphics-z@ICON_RES@

- jolla-settings-system-flashlight
- jolla-settings-networking-multisim

- geoclue-provider-mlsdb
- csd
- mapplauncherd-booster-silica-qt5-media

# NFC
- nfcd-mce-plugin
- nfcd-dbuslog-plugin
- jolla-settings-system-nfc

Summary: Jolla Configuration h4213

